### ISSUE TITLE
can i know input time?

### ISSUE THREAD

**Issue by saeu5407** [mpc001/auto_avsr#2]
Hello, thank you for sharing a great model.

I leave an issue with a question.

1. What is the time dimension that goes into the input of the model? (In the paper, we found that the fps is 25 but not the time dimension.)

2. What happens if I put a video longer than the input time dimension?

Thank you.

**Comment by mpc001** [comment]
Hello @saeu5407, we do not change the temporal resolution. Specifically, we use ResNet-18 as our visual front-end, and you can find more details about the input and output size for each layer in Table S2 on page 15 at [here](https://arxiv.org/pdf/2202.13084.pdf). Also, the temporal resolution is still the same in the conformer encoder. To summarise, whether you're referring to the front-end (ResNet-18) or back-end (conformer), the output time dimension will be the same size as the input time dimension for VSR.

**Comment by saeu5407** [comment]
Thank you for your answer!

Then, is there no problem with putting any length of video?

**Comment by mpc001** [comment]
Hi, there is no problem with putting any length of video.

**Comment by saeu5407** [comment]
thank you for your paper and answer
