### ISSUE TITLE
Question about training on a Chinese dataset created by myself.

### ISSUE THREAD

**Issue by liu33333** [mpc001/auto_avsr#31]
As your following guidence say:
![image](https://github.com/mpc001/auto_avsr/assets/96512084/188e2384-ca27-447b-a57b-077ee640cb4f)
I’m prepareing the .csv file. But I don't understand the last step.  The 'tokenize' method's output is a tensor. Should I transform the tensor to a list or use the tensor itself to create the .csv?
Thanks for your help.

**Comment by Kiri0824** [comment]
Have you solved this problem? I am facing the same problem.

**Comment by Kiri0824** [comment]
> As your following guidence say: ![image](https://private-user-images.githubusercontent.com/96512084/322174649-188e2384-ca27-447b-a57b-077ee640cb4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjcwMTksIm5iZiI6MTczMTQ2NjcxOSwicGF0aCI6Ii85NjUxMjA4NC8zMjIxNzQ2NDktMTg4ZTIzODQtY2EyNy00NDdiLWE1N2ItMDc3ZWU2NDBjYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAyNTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzJmOTU4N2JlYTViYjhlYTA3ZGUxYjliNjRhNGM5ODVmM2FhNDYyNjBmMGZkYWQxMThiYTZiNzhkZjdlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g7NAUvq30nBesCU9ihK7cHfAysxtEqfoP7RxNRVbLVk) I’m prepareing the .csv file. But I don't understand the last step. The 'tokenize' method's output is a tensor. Should I transform the tensor to a list or use the tensor itself to create the .csv? Thanks for your help.

Have you solved this problem? I am facing the same problem.

**Comment by Kiri0824** [comment]
> As your following guidence say: ![image](https://private-user-images.githubusercontent.com/96512084/322174649-188e2384-ca27-447b-a57b-077ee640cb4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Njc0MTcsIm5iZiI6MTczMTQ2NzExNywicGF0aCI6Ii85NjUxMjA4NC8zMjIxNzQ2NDktMTg4ZTIzODQtY2EyNy00NDdiLWE1N2ItMDc3ZWU2NDBjYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzMDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTc1ZTE2ZmIyMjA5MzM4MGQ0Y2I0YzVjOGExZTRlYjFmZjIyZGQzYTMyNzIxYjYwYzQyN2I2YzQ2ZWRkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LeolzDs86LbY1qCFL5l9ujgHvN3NQmhZ4RPqW_YywkY) I’m prepareing the .csv file. But I don't understand the last step. The 'tokenize' method's output is a tensor. Should I transform the tensor to a list or use the tensor itself to create the .csv? Thanks for your help.

Sorry to bother you, I have found the solution. I just need to process it according to the style in lines 307-309 of preprocess_lrs2lrs3.py. :)

**Comment by SajjadAemmi** [comment]
Hi my friend
Thank you for sharing your solution
I have a question, may you can help me

I want to train VSR on a Persian dataset created by myself.
i used `vsr_trlrs3_23h_base.pth` as pre-trained ckeckpoint and trained VSR model on a persian dataset with 10 seconds duration of each video.

But the trained model only learnd 1 text, and produced exactly the same text for every input videos in the inference time.

what is the problem?

**Comment by liu33333** [comment]
您好，
根据您的描述，我猜测有可能是SPM的问题，您是否使用波斯语的文本数据集训练了对应的SPM？如果使用仓库里给的则只能够生成英文的文本。
