### ISSUE TITLE
Issues training VSR from scratch

### ISSUE THREAD

**Issue by FGiuliari** [mpc001/auto_avsr#37]
Hi, I'm having some issues in getting good results when training the VSR only model from scratch.

This is a screenshot of the decoder eval curves for the (full training LRS only 438h).

The gray one is starting with your base_23h checkpoint -> which immediately starts learning well
The orange one  without loading any weights -> much slower learning
And the purple one is with my retraining on the 23h set.
![image](https://github.com/user-attachments/assets/68cf10f1-befe-4153-bf33-704ee770acb9)

You can see that my version of the 23h training is not good, as it's on par as just starting from zero.
also the WER on my 23h model is 1.01, not 0.96 as yours.

Am I missing something when doing the pretraining on the 23h set?

This is the code I am using, with everything else set as the default you provide in your config files.
```bash
python train.py 
  exp_dir=./exp/repretrain 
  exp_name=repretrain
  data.modality="video" 
  trainer.gpus=2 
  data.dataset.root_dir=preparation/prepro2 
  data.dataset.train_file=lrs3_train_transcript_lengths_seg24s_0to100.csv 
  data.dataset.val_file=lrs3_test_transcript_lengths_seg24s.csv 
  data.dataset.test_file=lrs3_test_transcript_lengths_seg24s.csv 
  optimizer.lr=0.0002 
```

This is the curves I get during the 23h pretraining

![image](https://github.com/user-attachments/assets/1d009a80-658d-404d-8d9c-d12f7126a223)

**Comment by FGiuliari** [comment]
Follow-up in case any other have the same issue.

I think the issues was with the "batch size" in terms of number of GPU used.
In my case I was using just 2 GPUs, while the Author said he was using 32 GPUs, which matters.

I solved by using gradient_accumulation=10 during the train of the 23h model and for the full 438h model, and now trains as it should.

**Comment by SajjadAemmi** [comment]
> Follow-up in case any other have the same issue.
> 
> I think the issues was with the "batch size" in terms of number of GPU used. In my case I was using just 2 GPUs, while the Author said he was using 32 GPUs, which matters.
> 
> I solved by using gradient_accumulation=10 during the train of the 23h model and for the full 438h model, and now trains as it should.

Hi my friend
Thank you for sharing your solution
I have a question, may you can help me

I want to train VSR on a Persian dataset created by myself.
i used `vsr_trlrs3_23h_base.pth` as pre-trained ckeckpoint and trained VSR model on a persian dataset with 10 seconds duration of each video.

But the trained model only learnd 1 text, and produced exactly the same text for every input videos in the inference time.

what is the problem?
