### ISSUE TITLE
How to use AUTO-AVSR to train a Chinese AVSR model

### ISSUE THREAD

**Issue by MiningIrving** [mpc001/auto_avsr#4]
How to use AUTO-AVSR to train a Chinese AVSR model, e.g. using CMLR data sets.Visual_Speech_Recognition_for_Multiple_Languages this project came to my attention.What is the relationship between this project and the AUTO-AVSR project

**Comment by mpc001** [comment]
Hi @MiningIrving, Auto-AVSR repository focuses on AV-ASR models and presents ASR, VSR, and AV-ASR results on LRS3 only, which includes both training and inference recipe. At this point, we have provided recipe for ASR and VSR models and will release AV-ASR recipe soon. The Visual_Speech_Recognition_for_Multiple_Languages repository focuses on VSR for multiple languages, which includes the inference recipe only. We have provided [instructions](https://github.com/mpc001/auto_avsr/blob/main/INSTRUCTION.md) to reconstruct a new dataset. Please feel free to review it.
