### ISSUE TITLE
Error merging 'config' with schema Key 'exp_dir' not in 'FairseqConfig'     full_key: exp_dir     object_type=FairseqConfig "Problem

### ISSUE THREAD

**Issue by Feiyunobug** [mpc001/auto_avsr#40]
Hello,

While running the training code, I encountered the following error:

python train.py \
    exp_dir="/root/autodl-tmp/pth/" \
    exp_name="gaofeiPTH" \
    data.modality="video" \
    data.dataset.root_dir="/root/autodl-tmp/auto_avsr" \
    data.dataset.train_file="train_cstm.csv"

sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/root/miniconda3/lib/python3.8/site-packages/hydra/main.py:94: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  _run_hydra(
Error merging 'config' with schema
Key 'exp_dir' not in 'FairseqConfig'
    full_key: exp_dir
    object_type=FairseqConfig
I was wondering if you have come across a similar issue before. Could this be caused by a version conflict between fairseq, hydra-core, and omegaconf? My package versions are:

hydra-core==1.3.2
omegaconf==2.3.0
fairseq==0.12.2
If you have any insights, I would really appreciate your help in understanding what might be causing this problem.

Thank you in advance for your time and assistance.

**Comment by SajjadAemmi** [comment]
@Feiyunobug How did you fix it?

**Comment by NikitaBigHead** [comment]
https://github.com/mpc001/auto_avsr/issues/3

**Comment by Feiyunobug** [comment]
Thank you, I have sloved this problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月30日(星期六) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mpc001/auto_avsr] Error merging &#39;config&#39; with schema Key &#39;exp_dir&#39; not in &#39;FairseqConfig&#39;     full_key: exp_dir     object_type=FairseqConfig &quot;Problem (Issue #40)














 
#3
