### ISSUE TITLE
How to get audio from mp4 using torchaudio

### ISSUE THREAD

**Issue by zyjcsf** [mpc001/auto_avsr#8]
Hi， when I run the preprocess_lrs2lrs3.py ， I got an error when 'audio_data = aud_dataloader.load_data(data_filename)' .
It seem that the sox do not support the mp4 files, how can i to solve it ?

Thank you very much.

**Comment by mpc001** [comment]
Hi @zyjcsf  one solution for extracting audio is `ffmpeg`. There are multiple ways to install `ffmpeg` libraries. If you are using Anaconda Python distribution, `conda install -c conda-forge ffmpeg` will install compatible FFmpeg libraries.

**Comment by zyjcsf** [comment]
Thank you very much

**Comment by techbyasad** [comment]
@mpc001 @zyjcsf I ran into the same issue.
'audio_data = aud_dataloader.load_data(data_filename)'

whereas the data_filename is an *.mp4 file

Are we expected to have .wav files in place when running the preprocessing?
