### ISSUE TITLE
Number of GPUs for training

### ISSUE THREAD

**Issue by naraysa** [mpc001/auto_avsr#9]
Hi, 

Thanks for releasing the training code for Auto-AVSR. I was curious to know the number of gpus used for training the model when using different amount of data like 23/438/3448 hours for LRS3. 

Thanks

**Comment by mpc001** [comment]
Hi @naraysa, I used 32 GPUs (A100-40GB) for 23-h/438-h experiments and 64 GPUs for 3448-hour experiments.
